{{- if .Values.config.create -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "template.fullname" . }}-config
  labels:
    {{- include "template.labels" . | nindent 4 }}
data:
  {{ .Values.config.name  }}: |
                              document.ENV = {
                                VITE_APP_NAME: 'Time Stamp Service',
                                VITE_APP_CHAIN_ID: '5',
                                VITE_APP_CTR_ADDRESS_TIMESTAMP: '0x7De85Ba2D41482c169c95BD074D2cbfcf99A0271'
                              }
{{- end }}
