{{- if .Values.config.create -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "template.fullname" . }}-config
  labels:
    {{- include "template.labels" . | nindent 4 }}
data:
  {{ .Values.config.name  }}: |
                              document.ENV = {
                                VITE_APP_NAME: 'Time Stamping Service',
                                VITE_APP_CTR_ADDRESS_TIMESTAMP_ETHEREUM: '0xC086319513834040Aa4910E4bdCf2b0e54A9D323',
                                VITE_APP_CTR_ADDRESS_TIMESTAMP_POLYGON: '0xCF84E18F1a2803C15675622B24600910dc2a1E13',
                                VITE_APP_CTR_ADDRESS_TIMESTAMP_Q: '0xB524653B3fDC900aA431894c36D02ed189e175B7',
                                VITE_APP_CTR_ADDRESS_POSEIDON_HASH_ETHEREUM: '0x4ca0b63a4473d9606b2802577e1fadc58ce369fd',
                                VITE_APP_CTR_ADDRESS_POSEIDON_HASH_POLYGON: '0x00df74062DCFe5D708eA34170319377fD1EDB9Ce',
                                VITE_APP_CTR_ADDRESS_POSEIDON_HASH_Q: '0x5cdA170e8C0Eb92cf4560d739edDDF8D09D2363A'
                              }
{{- end }}
